services:
  db:
    container_name: 69-s3-db
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:${DB_PORT:-54327}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: 69-s3-admin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "127.0.0.1:${PGADMIN_PORT:-8080}:80"
    depends_on:
      - db

  # --- เพิ่ม Service ของ App (Strapi) ---
  my_app:
    container_name: my_app
    image: prawee/strapi
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DB_NAME}
      DATABASE_USERNAME: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:${APP_PORT:-8083}:1337"
    depends_on:
      - db                         # รอให้ db สตาร์ทก่อน

volumes:
  pgdata: