version: '3.8'

services:
  db:
    container_name: 69-s3-db
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: patipan
      POSTGRES_PASSWORD: patipan
      POSTGRES_DB: postgres
    ports:
      - "54327:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: 69-s3-admin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

  # --- เพิ่ม Service ของ App (Strapi) ---
  my_app:
    container_name: my_app
    image: prawee/strapi
    restart: unless-stopped
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db           # ชี้ไปยังชื่อ service 'db' ด้านบน
      - DATABASE_PORT=5432         # ใช้พอร์ตภายในของ Container (5432) ไม่ใช่พอร์ตที่แมปออกข้างนอก (54327)
      - DATABASE_NAME=postgres     # ดึงค่าจาก POSTGRES_DB
      - DATABASE_USERNAME=patipan  # ดึงค่าจาก POSTGRES_USER
      - DATABASE_PASSWORD=patipan  # ดึงค่าจาก POSTGRES_PASSWORD
    ports:
      - "8083:1337"                # หลบพอร์ต 8080 ที่ชนกับ pgadmin มาใช้ 8083 แทน
    depends_on:
      - db                         # รอให้ db สตาร์ทก่อน

volumes:
  pgdata: